name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issueMessage = "👋 Welcome to our repository! We're glad you're here. If you have any questions, feel free to ask. Here's a guide to help you get started: [GETTING_STARTED](https://github.com/notsoocool/codecache/blob/main/GETTING_STARTED.md).";
            const prMessage = "🎉 Thank you for your pull request! We appreciate your contribution. Please review the following guidelines to ensure your PR meets our requirements: [GETTING_STARTED](https://github.com/notsoocool/codecache/blob/main/GETTING_STARTED.md).";

            if (context.issue) {
              const issueNumber = context.issue.number;
              const issueType = context.issue.pull_request ? 'pr' : 'issue';
              const message = issueType === 'pr' ? prMessage : issueMessage;

              // Post a comment on the issue or PR
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: issueNumber,
                body: message
              });
            }
